name: ci

on:
  pull_request:
    branches:
      # on pull requests to develop and release branches
      - develop
      - 'v*'

jobs:
  ndm-build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodule: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.5.1

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          file: ./build/ndm-build-base/Dockerfile
          push: false
          load: true
          platforms: linux/amd64
          tags: |
            openebs/ndm-build-base:ci
        
      - name: Run Trivy vulnerability scanner
        uses: aquase--recursivecurity/trivy-action@master
        with:
          image-ref: 'openebs/ndm-build-base:ci'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
